### PR TITLE
Remove external variable references

### PR DESCRIPTION
**Pull request by whikloj**
Update readme

### CODE REVIEW

**Comment by Natkeeran** [comment]
@whikloj 
I seem to be running into this issue while trying to test this PR.  Can you please rebase.  I can try again.  Thanks.



```
TASK [Islandora-Devops.fcrepo : Download fcrepo war] *************************************************************************************************
Tuesday 27 March 2018  12:25:47 -0400 (0:00:00.499)       0:05:48.290 ********* 
fatal: [default]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 165.227.41.144 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_OqotLp/ansible_module_get_url.py\", line 573, in <module>\r\n    main()\r\n  File \"/tmp/ansible_OqotLp/ansible_module_get_url.py\", line 421, in main\r\n    dest_is_dir = os.path.isdir(dest)\r\n  File \"/usr/lib/python2.7/genericpath.py\", line 49, in isdir\r\n    st = os.stat(s)\r\nTypeError: coercing to Unicode: need string or buffer, NoneType found\r\n", "msg": "MODULE FAILURE", "rc": 0}
``

**Comment by whikloj** [comment]
rebased, thanks @Natkeeran

**Comment by Natkeeran** [comment]
@whikloj 

Something is not right.  Deploying to a VM and getting the following error.  

```
TASK [Islandora-Devops.fcrepo : Download fcrepo war] ****************************************************************************************
Tuesday 27 March 2018  15:16:14 -0400 (0:00:00.462)       0:11:32.566 ********* 
fatal: [default]: FAILED! => {"changed": false, "module_stderr": "Shared connection to ###.##.###.### closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_4mSiv3/ansible_module_get_url.py\", line 573, in <module>\r\n    main()\r\n  File \"/tmp/ansible_4mSiv3/ansible_module_get_url.py\", line 421, in main\r\n    dest_is_dir = os.path.isdir(dest)\r\n  File \"/usr/lib/python2.7/genericpath.py\", line 49, in isdir\r\n    st = os.stat(s)\r\nTypeError: coercing to Unicode: need string or buffer, NoneType found\r\n", "msg": "MODULE FAILURE", "rc": 0}
```

**Comment by whikloj** [comment]
Yeah probably, we might need to add the `fcrepo_user` and `fcrepo_war_path` to the claw-playbook variables. I'll try to get some time to look at this.

**Pull request closed without merging**
